name: BuildIt
author: Schmoller

version: 1.0

main: au.com.mineauz.BuildIt.BuildIt

commands:
  /wand:
  /set:
  /replace:
  /naturalize:
  /undo:
  /redo:
  /offset:
  /copy:
  /cut: 
  /paste:
  /regen:
  /expand:
  /chunk:
  /generate:

permissions:
   buildit.wand:
     default: op
   buildit.copy:
     default: op
   buildit.cut:
     default: op
   buildit.paste:
     default: op
   buildit.undo:
     default: op
   buildit.set:
     default: op
   buildit.replace:
     default: op
   buildit.naturalize:
     default: op
   buildit.regen:
     default: op
   buildit.expand:
     default: op
   buildit.chunk:
     default: op
   buildit.generators.sphere:
     default: op