name: BuildIt
author: Schmoller

version: 1.0

main: au.com.mineauz.BuildIt.BuildIt

commands:
  /wand:
    description: "Gives you a selection wand"
  /set:
    description: "Sets the selections contents to something"
  /replace:
    description: "Replaces the selections contents with something"
  /undo:
    description: "Undoes the last action"
  /redo:
    description: "Redoes the last undone action"
  /offset:
    description: "Offsets the current selection"
  /copy:
    description: "Copies the selection"
  /cut:
    description: "Cuts the selection"
  /paste:
    description: "Pastes the selection"
