name: BuildIt
author: Schmoller

version: 1.0

main: au.com.mineauz.BuildIt.BuildIt

commands:
  /wand:
    description: "Gives you a selection wand"
  /set:
    description: "Sets the selections contents to something"
  /undo:
    description: "Undoes the last action"
  /redo:
    description: "Redoes the last undone action"
